version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: rssdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rss-app:
    build: .
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=rssdb;Username=postgres;Password=yourpassword

volumes:
  postgres_data: